### PR TITLE
Initial commit to add 'warn' option for issue #63.

### PR DESCRIPTION
**Pull request by wburningham**
@loeffel-io [per your invitation](https://github.com/loeffel-io/ls-lint/issues/63#issuecomment-963983943) here is a PR with a simple change to support a 'warn' flag.

### CODE REVIEW

**Comment by wburningham** [comment]
@loeffel-io do you have any feedback on this PR?

**Comment by loeffel-io** [comment]
Hey @wburningham, 

thanks for your PR! 

LGTM, the only thing i would love to see before testing is that i would love to move the logger to the top including the exit code declaration and logWriter (would love to avoid `w` as name) to use the logger also for the log error messages above

**Comment by loeffel-io** [comment]
btw after that we should think about a good place in the docs for it

**Comment by wburningham** [comment]
> to use the logger also for the log error messages above

When using `-w` and if there is an unexpected system error I would think that you would still want those errors to go to stderr instead of stdout. I think `-w` should configure the output of the lining errors only (not unexpected errors). 

I can still hoist the declaration of `logWriter` to the top of the file, but I think `logWriter` should only be used for the failed rules.

Thoughts?

**Comment by wburningham** [comment]
> after that we should think about a good place in the docs for it

If you give me access to the docs repo I can submit another PR.

**Comment by wburningham** [comment]
@loeffel-io just following up on my question about using stdout for lint warnings only with ‘-w’ and access to a docs repo.

**Comment by wburningham** [comment]
@loeffel-io just following up on my question about using stdout for lint warnings only with ‘-w’ and access to a docs repo.

**Comment by loeffel-io** [comment]
Hey @wburningham, 

sorry for the delay. Anyways, i am going to merge the PR and update the documentation and order myself. 

Thank you very much! 🙏  ❤️

**Comment by loeffel-io** [comment]
You can double check the new order here: https://github.com/loeffel-io/ls-lint/blob/update/loeffel/go/main.go

**Comment by wburningham** [comment]
Sounds good. I await for the v1.10.0 release so I can use the docker image.

**Comment by wburningham** [comment]
I saw that you just released v1.11.0. It looks like the docker image is not published automatically. Can you run the script/build to build and publish the v1.11.0 docker image?

**Comment by loeffel-io** [comment]
Bildschirmfoto 2022-02-24 um 11 28 58

**Comment by loeffel-io** [comment]
you are right, the docs are wrong 

needs to be `1.11.0` instead of `v1.11.0`

**Comment by loeffel-io** [comment]
btw mentioned you here: https://ls-lint.org/1.x/prologue/contributions.html#issues <3

**Comment by wburningham** [comment]
Thanks for the mention!

**Pull request merged**
