### PR TITLE
Add linux/ppc64le and linux/s390x builds

### PR DESCRIPTION
**Pull request by yselkowitz**

### CODE REVIEW

**Comment by levivic** [comment]
hi @loeffel-io , could someone review/merge this PR?

**Comment by manojnkumar** [comment]
@loeffel-io :  Following up on this.  Could you review/merge this?

**Comment by loeffel-io** [comment]
hey folks,

drone cloud is not supporting ppc64le which makes it impossible to build the ppc64le image with the current setup as you can see here: https://cloud.drone.io/loeffel-io/ls-lint/110

please let me know if you have any idea to solve this issue

**Comment by loeffel-io** [comment]
@yselkowitz do you need only the binaries or a docker image? i would be fine when we just release the binaries

**Comment by yselkowitz** [comment]
@loeffel-io let's start with that, as it's my higher priority and should be straigh-forward.  I have rebased my patch to handle just that for now, and we can address the containers -- and the changes to CI that it would enable -- afterwards in a separate PR.

**Comment by loeffel-io** [comment]
thanks @yselkowitz! pretty sure that the binaries are missing for the github release https://github.com/loeffel-io/ls-lint/blob/master/.drone.yml#L48

**Comment by loeffel-io** [comment]
fyi: https://cloud.drone.io/loeffel-io/ls-lint/113

**Comment by loeffel-io** [comment]
fyi: v2 is on the way and comes with s390x support. ppc64le is blocked through https://github.com/loeffel-io/ls-lint/blob/feature/loeffel-io/v2/cmd/ls_lint/target.bzl#L1. docker support is blocked through https://github.com/bazelbuild/rules_docker/issues/1599

**Comment by loeffel-io** [comment]
With v2.x s390x build are available: https://github.com/loeffel-io/ls-lint/releases/tag/v2.0.0-beta.0

Feel free to try it out

**Comment by loeffel-io** [comment]
ref: https://github.com/bazelbuild/platforms/pull/64

**Comment by loeffel-io** [comment]
This feature is now available in the `v2.3.0-beta.1` release. 
Please test it and let me know if there are any issues ❤️ 

The upcoming v2.3.0 blog post: https://ls-lint.org/blog/announcements/v2.3.0.html
The release notes: https://github.com/loeffel-io/ls-lint/releases/tag/v2.3.0-beta.1

**Pull request closed without merging**
