### PR TITLE
feat: add wildcard extension support

### LINKED ISSUE #56: Wildcard support for file extensions?
Hi!

First of all, I'd like to say that I love this! Exactly what I was looking for! Thanks!

One feature that seems to be missing (or would be great to have) is the option to set a general rule for all files. Specifically to say that all files and folders should be lowercase, regardless of their extension.

It seems that something like this isn't possible:

```yml
ls:
    .*: lowercase
    .dir: kebab-case
    .js: kebab-case
    ...
```

Correct?

The alternative would be to find out what extensions are in a project and what extensions could come up in the future, which isn't really feasible.

Or do you have another idea?

Thanks in advance!

### LINKED ISSUE #177: Feature proposal: support for mixed kebab and point case
Hello,

Considering both Angular and NestJS use the same file naming conventions (names separated by dashes, separated from the type by dots, e.g. user-session.service.ts), it would be great to have in-built support for this, either by adjusting the existing point.case to allow dashes in the name part of the file name, or adding a new case.

Thanks

### PR DESCRIPTION
**Pull request by loeffel-io**
close #56 
close #177 
ref #70

### CODE REVIEW

**Comment by what1s1ove** [comment]
Hey @loeffel-io ! Thank you for all you do!

Is this not yet released in any version?

**Comment by loeffel-io** [comment]
> Hey @loeffel-io ! Thank you for all you do!
> 
> Is this not yet released in any version?

Hey, it will be released in v2.3.0 but there is still some work to do - I’ll keep you updated

**Comment by loeffel-io** [comment]
This feature is now available in the `v2.3.0-beta.1` release. 
Please test it and let me know if there are any issues ❤️ 

The upcoming v2.3.0 blog post: https://ls-lint.org/blog/announcements/v2.3.0.html
The docs: https://ls-lint.org/2.3/getting-started/introduction.html
The release notes: https://github.com/loeffel-io/ls-lint/releases/tag/v2.3.0-beta.1

**Comment by what1s1ove** [comment]
Sure, here's the translated message:

Hi Lucas! Thank you for everything you do!

I've migrated to the new version, and everything is working as expected! Thank you! Here you can find the pull request for the migration https://github.com/what1s1ove/whatislove.dev/pull/680.

However, I have one question. I'm not sure if it's related to this version or not. I have a `CHANGELOG.md` file that exists in each of the packages and in the root directory.

```
packages/package-1/
  CHANGELOG.md
packages/package-2/
  CHANGELOG.md
CHANGELOG.md
```
Currently, I have this rule in the ls-lint config:

```yml
ls:
  '**':
    CHANGELOG.md: SCREAMING_SNAKE_CASE
```

But I still have to add the root `CHANGELOG.md` to ignore, as the rule doesn't apply to it.

```yml
ls:
  '**':
    CHANGELOG.md: SCREAMING_SNAKE_CASE

ignore:
  - CHANGELOG.md

```

Could you help me with this? I would like to avoid adding the root `CHANGELOG.md` file to ignore. Here you can find a link to the repository with an example https://github.com/what1s1ove/whatislove.dev

**Comment by loeffel-io** [comment]
`**` match only sub directories of root - i will give you more details about your PR in your PR

**Pull request merged**
