### PR TITLE
Add glob support to ignores

### PR DESCRIPTION
**Pull request by hanneskaeufler**
As is on the v2 wishlist and was mentioned in https://github.com/loeffel-io/ls-lint/issues/35 and https://github.com/loeffel-io/ls-lint/issues/56#issuecomment-909418833, globbing is currently not allowed for the `ignore` key.

This is a first try at implementing this.

* [x] Performance implications?
* [ ] Documentation?
* [ ] Haven't found a changelog

### Performance

All measurements done on an 2020 M1 MacBook Air with 8GB of ram.
Using hyperfine, I ran `hyperfine './ls-lint'` with the current local build of ls-lint as well as with master. I did a couple variations, based on the [example config](https://github.com/loeffel-io/ls-lint/blob/master/examples/nuxt-nuxt-js/.ls-lint.yml):

| build | config | result |
| ----- | ------ | ------ |
| this branch | with `node_modules` in ignore | `Time (mean ± σ):      16.0 ms ±   0.8 ms    [User: 7.4 ms, System: 8.7 ms]` |
| this branch | with `'**/node_modules'` in ignore | `Time (mean ± σ):     282.4 ms ±  21.8 ms    [User: 71.7 ms, System: 210.1 ms]` |
| master | with `node_module` in ignore | `Time (mean ± σ):      15.9 ms ±   0.7 ms    [User: 7.3 ms, System: 8.7 ms]` |

This kind of confirms what makes some sense: If you use a glob in ignores, depending on the size of your project, you pay a _significant_ penalty in performance. If you don't use any globs, you don't pay measurably.

### CODE REVIEW

**Comment by loeffel-io** [comment]
Great! Thanks for the PR! I am currently on vacation and get back to you asap

**Comment by MagnusHJensen** [comment]
What's the status on this? Really needed for monorepo structure

**Comment by hanneskaeufler** [comment]
@loeffel-io friendly ping :) Anything I can do to move this along? Thanks!

**Comment by GeorgeTaveras1231** [comment]
Would be great to get this merged and published. There doesn't seem to be a good way to ignore certain folder names in arbitrary locations in a repo. I have a monorepo with multiple __tests__ folders that I would like to ignore.

**Comment by loeffel-io** [comment]
Hey folks,

sorry that this takes so long - the support will come! This will come together with https://github.com/github/super-linter/issues/2505#issuecomment-1263886322 as soon i have enough mind capacity

**Comment by ProjectBarks** [comment]
@loeffel-io Is there anything we can do to help get this merged? Seems like it has been stale for a bit.

**Review by loeffel-io — CHANGES_REQUESTED** [review]
thank you @hanneskaeufler! 

The tests are not meaningful enough imo - we should add ignore mid path tests and some more ignore variations. 

is there a reason for removing the `globIndex` func from the `config` struct? 

thanks!

**Comment by dror-weiss** [comment]
ping from here as well; I need glob support in the `ignore` section for my monorepo 🙏🏻

**Comment by gbrandt1** [comment]
no support for ignore globs is a show-stopper for me.

**Comment by loeffel-io** [comment]
Very happy to announce that v2.0.0-beta.0 is now available: https://github.com/loeffel-io/ls-lint/releases/tag/v2.0.0-beta.0
Please see the changelog for any additional info: https://ls-lint.org/2.0/prologue/changelog.html#v2-0-0-beta

This feature (add glob support to ignores) is planned for `v2.1`
I will close this PR for now (there will be a new one)

**Comment by loeffel-io** [comment]
This is now supported with `v2.1.0-beta.0` 🎉  feel free to test it! 
more infos: https://github.com/loeffel-io/ls-lint/pull/119

**Pull request closed without merging**
